name: Security tests

on:
  pull_request:
    branches: [ alpha, beta, prod ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Check code formatting
      run: npm run format:check
    
    - name: Run tests (if you add them later)
      run: npm test || true 